### ISSUE TITLE
[v1.0.0-alpha (Feature)] Compatibility with IE 11 / ES5

### ISSUE THREAD

**Issue by roux1max** [webpack-contrib/html-loader#193]
**I'm submitting a feature request**

**Webpack version:**
4.27.1

**HTML-Loader version:**
1.0.0-alpha.0

**Please tell us about your environment:**
Linux

**Current behavior:**
The generated scripts for importing an html template contains characters invalid for IE 11 (cannot specifically isolate them). So when I try to load my app on IE 11, it crashes with an error "invalid character at line ...".

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
N/A

* **What is the expected behavior?**
The generated scripts for importing an html template are compatible with IE 11 so that the application can be loaded on IE 11.

* **What is the motivation / use case for changing the behavior?**
Compatibility with older browser / Babel

 
* **Browser:** Internet Explorer 11
 
* **Language:** ES5

**Comment by philipbordallo** [comment]
@roux1max I ran into this same issue, it's because the content being loaded with the alpha version of **html-loader** will end up as a template literal with backticks ` `` `, which [isn't supported by IE11](https://caniuse.com/#feat=template-literals).

So if you need ES5 support, you are going to need something to transpile those template literals. [Babel](https://babeljs.io) and [babel-loader](https://github.com/babel/babel-loader) should do the trick, just make sure to use it before **html-loader** in the rule.

```js
{
  test: /\.(html)$/,
  use: [
    { loader: 'babel-loader' },
    { loader: 'html-loader' },
  ]
}
```

**Comment by evilebottnawi** [comment]
Do not use alpha version, it is not ready for production, we will do stable release new version in near future with no problems for IE
