### ISSUE TITLE
How to exclude resolving of some links? 

### ISSUE THREAD

**Issue by mihalt** [webpack-contrib/html-loader#198]
Hi! I use 

```
loader: 'html-loader',
    options: {
        attrs: [':href', 'img:src'],
    }
```
I need resolve a lot of href links, but any I don't want to resolve. For example skype links, wich are something like this skype:username?chat. Html loader thinks, that I resolve ./skype:username?chat.

How can I resolve my problem?

**Comment by mihalt** [comment]
May be I need to use ignoreCustomFragments, but don't understand how is it used.

**Comment by Justinohallo** [comment]
Hey Mihalt, 

I just spent the last few hours figuring why my code would not compile, and the reason is that I had a number of anchor tags with an href="#". This will not compile, and you can simply remove the empty href from the attribute list. <a class='btn'> Buy Now </a> . 

I was simply experimenting with this setup and haven't routed my links properly. The error message was not very clear as to why it was failing, but I am relatively new to programming and may be missing some critical understanding.

**Comment by mihalt** [comment]
@Justinohallo How is it connected with resolving of skype links?
