### ISSUE TITLE
Double quotes for attributes are removed

### ISSUE THREAD

**Issue by chua1989** [webpack-contrib/html-loader#306]
- Operating System: windows 10
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.41.5
- html-loader Version: 1.1.0

### Expected Behavior
\<link rel="shortcut icon" href="data:image/vnd.microsoft.icon;base64,AAABAAEAIC.....A/wAAAf+AAAH/jgBx/5+D+f//E////7//8=">

### Actual Behavior
 Error: html-webpack-plugin could not minify the generated output.
  In production mode the html minifcation is enabled by default.
  If you are not generating a valid html output please disable it manually.
  You can do so by adding the following setting to your HtmlWebpackPlugin config  :
  |
  |    minify: false
  |
  See https://github.com/jantimon/html-webpack-plugin#options for details.
  For parser dedicated bugs please create an issue here:
  https://danielruf.github.io/html-minifier-terser/
  Parse Error: <link rel="shortcut icon" href=data:image/vnd.microsoft.icon;base  64,AAABAAEAIC......A/wAAAf+AA  AH/jgBx/5+D+f//E////7//8=> 

### Code
```js
// webpack.config.js
            {
                test: /\.(png|jpe?g|gif|svg|ico)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('img/[name].[hash:7].[ext]'),
                    publicPath: '/'
                }
            }, {
                test: /\.html$/,
                loader: 'html-loader',
                options: {
                    minimize: true,
                    attributes: {
                        root: path.resolve(__dirname, '../src'),
                        list: [
                           {
                                tag: 'link',
                                attribute: 'href',
                                type: 'src'
                            }
                        ]
                    }
                }
            }
```

```html
// index.html
<head>
    ...
    <link rel="shortcut icon" href="/assets/img/favicon.ico">
</head>
```

// But when I set  **minimize**  like this, I got the desired result
```js
            {
                test: /\.html$/,
                loader: 'html-loader',
                options: {
                    minimize: {
                        caseSensitive: true,
                        collapseWhitespace: true,
                        conservativeCollapse: true,
                        keepClosingSlash: true,
                        minifyCSS: true,
                        minifyJS: true,
                        removeComments: true,
                        removeRedundantAttributes: true,
                        removeScriptTypeAttributes: true,
                        removeStyleLinkTypeAttributes: true,
                    },
                    attributes: {
                        root: path.resolve(__dirname, '../src'),
                        list: [
                            {
                                tag: 'link',
                                attribute: 'href',
                                type: 'src'
                            }
                        ]
                    }
                }
            }
```

**Comment by evilebottnawi** [comment]
It was fixed in master, anyway it is bug on https://github.com/DanielRuf/html-minifier-terser side

**Comment by evilebottnawi** [comment]
@chua1989 Does using `minimize: false` fix the issue?

**Comment by DanielRuf** [comment]
It's not a bug imho as attributes can be without quotes but only if there is one value (without spaces).
There is an option to prevent this, so why do you want to disable minification in general?

Please see the documented options:
![image](https://user-images.githubusercontent.com/827205/90139094-300a0b00-dd78-11ea-918a-cca9cf9aea87.png)

http://perfectionkills.com/experimenting-with-html-minifier/#remove_attribute_quotes

The default value is `false` so this should not happen by default. As I can see you set it to `true` before / in previous releases.

https://github.com/webpack-contrib/html-loader/commit/03152b1d3b807a287d84302f6a9987ceb22d395c

I guess this will be resolved when you release the new code. So nothing to do from my side.

**Comment by evilebottnawi** [comment]
@DanielRuf no, it is bug, `removeAttributeQuotes` remove attributes only when it is safe, it is keep attributes where it necessary, here example when developers use `data` and quotes are stripped, but according docs they shouldn't be removed

**Comment by evilebottnawi** [comment]
Look at example in docs:
```
 var input = '<p class="foo-bar" id="moo" title="blah blah">foo</p>';
  var output = minify(input, { removeAttributeQuotes: true });

  output; // '<p class=foo-bar id=moo title="blah blah">foo</p>'
```

quotes do not stripped on `title` attribute

**Comment by DanielRuf** [comment]
There are good reasons why this is disabled by default and set to `false` ;-)
PRs and clear use cases might be helpful to see if there is some change needed or if the docs are just not correct. But so far: I advise to not enable values which are disabled by default which could break specific code.

This is probably just a use case which is not covered by the current logic and not mentioned in the docs. As it is a single string without spaces it is handled as one string and so the quotes are correctly removed.

As you can see here, it works without quotes: https://codepen.io/DanielRuf/pen/wvGMpaz
The only problem is the parsing error due to the `data:...;...` markup.

**Comment by DanielRuf** [comment]
The examples probably contain no `data:...` examples. I think you mix things up a bit. Removing the quotes here should be fine.

**Comment by DanielRuf** [comment]
So far I can not reproduce it at the current demo page (well the base64 code looks a bit weird and seems to scramble the markup):

![image](https://user-images.githubusercontent.com/827205/90141706-c2f87480-dd7b-11ea-8a5b-aae0fdd71434.png)

If there is a small reproducible testcase with the full code I could take a look at it.

![image](https://user-images.githubusercontent.com/827205/90141823-eb806e80-dd7b-11ea-889f-5b34a98f8e7e.png)

But I don't think that it is caused by this option, also because it is not quite clear which option causes this.

**Comment by DanielRuf** [comment]
code:
> ```
> <link rel="shortcut icon" href="/assets/img/favicon.ico">
> ```

error:

> Parse Error: <link rel="shortcut icon" href=data:image/vnd.microsoft.icon;base 64,AAABAAEAIC......A/wAAAf+AA AH/jgBx/5+D+f//E////7//8=>

For me it looks like this is from the html-loader which inlines stuff?

**Comment by evilebottnawi** [comment]
Found a bug on parser side, try to put:
```
<link rel="shortcut icon" href=data:image/vnd.microsoft.icon;base 64,AAABAAEAIC......A/wAAAf+AA AH/jgBx/5+D+f//E////7//8=>
```

https://danielruf.github.io/html-minifier-terser/

And you will see the error, but it is valid HTML

**Comment by DanielRuf** [comment]
> <link rel="shortcut icon" href=data:image/vnd.microsoft.icon;base 64,AAABAAEAIC......A/wAAAf+AA AH/jgBx/5+D+f//E////7//8=>

This is not a valid base64 string imho. Please check what the html-loader generates and provide a full reproducible test with a valid base64 string (no ... and ////7//8 which seems to come from your side) ;-)

**Comment by evilebottnawi** [comment]
@DanielRuf we don't generate `data:` protocol in `html-loader` :facepalm:

**Comment by evilebottnawi** [comment]
Anyway I want to close issue, because here error from `html-webpack-plugin`, also I don't have reproducible test repo, so I can't investigate it deeply

**Comment by DanielRuf** [comment]
Well, probably happens due to url-loader and so on - which is enabled with the attributes option as far as I can see.

But I do not know much about the logic in html-loader.


<img width="631" alt="Bildschirmfoto 2020-08-13 um 19 00 32" src="https://user-images.githubusercontent.com/827205/90164635-f21cdf00-dd97-11ea-9a8b-50965ad7feda.png">
<img width="895" alt="Bildschirmfoto 2020-08-13 um 19 00 56" src="https://user-images.githubusercontent.com/827205/90164643-f47f3900-dd97-11ea-8476-43b2fc51f06e.png">
<img width="864" alt="Bildschirmfoto 2020-08-13 um 19 01 07" src="https://user-images.githubusercontent.com/827205/90164645-f5b06600-dd97-11ea-9154-9a8d2dc004d9.png">
<img width="408" alt="Bildschirmfoto 2020-08-13 um 19 02 06" src="https://user-images.githubusercontent.com/827205/90164651-f6e19300-dd97-11ea-82c5-ba1d9b6800f8.png">
<img width="711" alt="Bildschirmfoto 2020-08-13 um 19 06 35" src="https://user-images.githubusercontent.com/827205/90164801-21cbe700-dd98-11ea-9f06-cb9784ce9b42.png">

**Comment by evilebottnawi** [comment]
Thanks for investigation, I will look at this in near future

**Comment by BenjaminWFox** [comment]
That's for all the info & discussion here. I just encountered this issue with data:urls and, if it helps you (or anyone else) I discovered I had minification happening in `html-loader` and `html-webpack-plugin`.

Disabling minification in either one or the other of these fixed the error & correctly parsed the html for minification.

**Comment by evilebottnawi** [comment]
Fixed in master
