### ISSUE TITLE
Documentation for `minimize` option

### ISSUE THREAD

**Issue by JaKXz** [webpack-contrib/html-loader#81]
Continued from https://github.com/webpack/html-loader/pull/34#issuecomment-238993143 - I should have made a new issue in the first place, my bad.

Anyway, my question is where is the `minimize` option documented? Are there options I can pass to it? Is it on or off by default? I have looked up and down the docs, but I only saw the comment about `--optimize-minimize` which I'm not sure does anything 😕 

After looking through the source a bit, I've enabled it explicitly with:

``` js
htmlLoader: {
  minimize: true
}
```

but I'm not really sure if there is a difference being made on the HTML I'm loading in (via other loaders in the pipeline).

**Comment by bfricka** [comment]
There is a difference, and you're doing it correctly. Although the option isn't particularly well documented, it's mainly b/c it assumes you understand well how Webpack works (I can't say I do yet).  But, looking at the source it's pretty clear.

First it looks for a config query string as the key name (e.g. `html?config=fooKey`) which corresponds to the key in the webpack config. Defaults to `htmlLoader` which is what you're using.

Later it looks for the `minimize` boolean on the config. This sort of sucks, and you can see why later. If minimize is true, it sets its defaults from [html-minifier](https://github.com/kangax/html-minifier). Then it merges the entire config with the defaults, and passes it to html-minifier.

That's the sucky part because it's a pretty messy way to invoke the minifier. If html-minifier ever did a config validation that threw errors it would break this loader.

A better solution would be to just check `if (config.minimize)`, and accept either a boolean (to use defaults) or an object that takes html-minifier options.

**Comment by bfricka** [comment]
To be clear what I mean in the last paragraph:

```js
{
  module: {loaders: [{test: /\.html$/, loader: 'html'}]},
  htmlLoader: {
    minimize: {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      removeAttributeQuotes: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeRedundantAttributes: false,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true
    }
  }
}
```

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0-alpha.0
